# data params
datasource: opus_books
lang_src: ru
lang_tgt: it

# model params
batch_size: 8
num_epochs: 10
lr: 0.0001
max_len: 250
d_model: 512
tr_frac: 0.95

# folder paths to save model artifacts
model_folder_name: weights
experiment_folder_name: runs
tokenizer_folder_name: tokenizers
