datasource: opus_books
lang_src: ru
lang_tgt: it

path_to_texts: texts
path_to_model_weights: weights
path_to_experiments: runs
path_to_tokenizers: tokenizers

tr_frac: 0.95
max_len: 250
batch_size: 32
num_epochs: 10

embed_size: 512
hidden_size: 2048
dropout: 0.1
heads: 8
layers: 6